### ISSUE TITLE
unknown magic error

### ISSUE THREAD

**Issue by ThomasLeister** [ThomasLeister/mod_serverinfo#4]
@imolein is facing unknown error resulting in 500 page. Caused by count registered loop.

**Comment by imolein** [comment]
Yesterday I could figure out that it has something to do with this `usertable = hosts[host].users:users()`. I can see in the log that it tried to get the information from the database, but can't say why it failed, because it don't log anything about it.
But I think this issue is obsulet, cause of the new structure, where the registered users are not counted.

**Comment by ThomasLeister** [comment]
Jepp, this issue is obsolete.
